### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by clankill3r** [gingerBill/JaiLang#1]
Can you explain how we can install JaiLang?

**Comment by gingerBill** [comment]
If you have package control installed, add the repository `https://github.com/gingerBill/JaiLang` and then install as normal (package control: install -> JaiLang).

If you want to do it manually, just download as a zip and rename the extension as .sublime-package and place in your package directory.

**Comment by clankill3r** [comment]
Thanks!
To complete (for mac):

Sublime > preferences > browse packages

That will bring you to finder. I just dropped the content in the user folder in a folder named jaiLang and it worked.
